"""Abstract protocol that every database provider must satisfy."""
from __future__ import annotations

from typing import Protocol


class DBProvider(Protocol):
    """Contract for all database backends. Swap providers via DB_PROVIDER env var."""

    def ensure_schema(self) -> None: ...

    # -- Assets --

    def add_asset(
        self,
        name: str,
        category: str,
        brand: str | None,
        model: str | None,
        serial: str | None,
        purchase_date: str | None,
        purchase_price: float | None,
        warranty_expiry: str | None,
        location: str | None,
        notes: str | None,
        plant_species: str | None,
        plant_size: str | None,
        planting_date: str | None,
        plant_notes: str | None,
        user_id: str,
    ) -> dict: ...

    def list_assets(self, user_id: str, category: str | None = None) -> dict: ...
    def search_assets(self, user_id: str, query: str) -> dict: ...

    def log_maintenance(
        self,
        user_id: str,
        asset_id: int,
        task_name: str,
        completed_date: str | None,
        cost: float | None,
        notes: str | None,
        next_due_date: str | None,
        interval_days: int | None,
    ) -> dict: ...

    def get_upcoming_maintenance(self, user_id: str, days_ahead: int = 30) -> dict: ...
    def get_asset_history(self, user_id: str, asset_id: int) -> dict: ...
    def update_asset(self, user_id: str, asset_id: int, updates: dict) -> dict: ...
    def delete_asset(self, user_id: str, asset_id: int) -> dict: ...
    def list_maintenance_tasks(self, user_id: str, since_date: str | None = None) -> list[dict]: ...

    # -- Auth / Users --

    def authenticate(self, email: str, password: str) -> dict | None: ...
    def list_users(self) -> list[dict]: ...
    def get_user(self, user_id: str) -> dict | None: ...
    def email_exists(self, email: str) -> bool: ...
    def create_user(self, email: str, password: str, role: str = "user") -> dict: ...
    def set_active(self, user_id: str, is_active: bool) -> None: ...
    def set_role(self, user_id: str, role: str) -> None: ...
    def reset_password(self, user_id: str, new_password: str) -> None: ...
    def delete_user(self, user_id: str) -> None: ...
    def is_last_active_admin(self, user_id: str) -> bool: ...
    def bootstrap_admin(self) -> None: ...

    # -- Long-term (key-value) memory --

    def memory_set(
        self, user_id: str, agent_name: str, key: str, value: str, updated_at: str
    ) -> None: ...

    def memory_get(self, user_id: str, agent_name: str, key: str) -> str | None: ...
    def memory_delete(self, user_id: str, agent_name: str, key: str) -> None: ...
    def memory_get_all(self, user_id: str, agent_name: str) -> list[dict]: ...

    # -- Semantic memory --

    def semantic_store(
        self, agent_name: str, content: str, embedding: str, metadata: str
    ) -> int: ...

    def semantic_retrieve(self, agent_name: str) -> list[dict]: ...
    def semantic_clear(self, agent_name: str) -> None: ...
